- name: show return value of command module
  hosts: all
  become: true
  gather_facts: no
  tasks:
          - name: capture output of id command
            command: id -un
            register: login
          - debug: msg="{{ login.stdout }}"
