- name: Configure webserver with nginx
  hosts: all
  become: True
  become_method: sudo
  tasks:
    - name: install nginx
      yum:
        name: nginx
        state: latest

    - name: copy nginx config file
      copy: src=files/nginx.conf dest=/etc/nginx/conf.d/default.conf

    - name: copy index.html
      template: src=templates/index.html dest=/usr/share/nginx/html/index.html mode=0644

    - name: restart nginx
      service: name=nginx state=restarted