- hosts: all
  become: true
  gather_facts: no
  tasks:
    - name: fetch redhat user from shell script
      script: scripts/accinv.sh
      register: userlist
    - name: Write result to output.csv
      delegate_to: localhost
      lineinfile:
        path: /tmp/output.csv
        line: "{{ userlist.stdout_lines | join('\n') }}"
        create: yes
        state: present      