- hosts: all
  become: true
  gather_facts: no
  tasks:
    - name: Read PermitRootLogin from /etc/ssh/sshd_config
      shell: "grep -E '^PermitRootLogin\\s*' /etc/ssh/sshd_config | cut -d ' ' -f 2"
      register: result
    - set_fact: PermitRootLogin="{{ inventory_hostname }},/etc/ssh/sshd_config,PermitRootLogin,{{ result.stdout }}"
    - name: Read SELINUX from /etc/selinux/config
      shell: "grep -E '^SELINUX=' /etc/selinux/config | cut -d '=' -f 2"
      register: vresult
    - set_fact: selinux="{{ inventory_hostname }},/etc/selinux/config,SELINUX,{{ result.stdout }}"
    - name: Write result to output_cm.csv
      delegate_to: localhost
      lineinfile:
        path: /tmp/output_cm.csv
        line: "{{ item.line }}"
        create: yes
        state: present
      when: item.line | length > 0
      loop:
        - line: "{{ PermitRootLogin }}"
        - line: "{{ selinux }}"
      ignore_errors: yes     
