- hosts: all
  become: true
  gather_facts: no
  tasks:
    - name: check lslogin installed
      shell: command -v lslogins >/dev/null 2>&1
      register: lslogins_present
      ignore_errors: yes
    - name: get realm info
      shell: "realm list | grep domain-name | cut -d: -f2"
      register: realm_info
      ignore_errors: yes
    - debug: msg="{{ realm_info }}"
    - name: fetch linux user from shell script
      script: scripts/inv_lnx_user_lslogins.sh
      register: userlist
      when: lslogins_present.rc == 0
    - name: fetch ad user from shell script
      script: scripts/inv_lnx_ad_user.sh
      register: userlist
      when: realm_info.rc == 0
    - name: Write result to output.csv
      delegate_to: localhost
      lineinfile:
        path: /tmp/output.csv
        line: "{{ userlist.stdout_lines | join('\n') }}"
        create: yes
        state: present 
      ignore_errors: yes     